version: '3.8'

services:
  app:
    build: .
    container_name: portfolio-app
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
